name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: 1.0.2
      - name: Validate all locale files
        run: yarn validate
